package projects.GA.nodes.messages;

import java.util.ArrayList;
import java.util.List;

import projects.GA.nodes.nodeImplementations.GANode;
import projects.GA.utils.GATree;
import sinalgo.nodes.messages.Message;

/**
 * Message generated by the sink to set the route according
 * to the GA algorithm's output.
 * @author edson
 *
 */
public class SetRouteMessage extends Message{

	public int SenderID;
	public int hopToSink;
	public int numTree; //This is the number of trees
	public ArrayList<GATree> trees;
	
	public SetRouteMessage(int sender, int hopToSink, int numTree){
		SenderID = sender;
		this.hopToSink = hopToSink;
		this.numTree = numTree;
		trees = new ArrayList<GATree>();
		GANode.debugMsg("Created a SRM by node "+ this.SenderID + " which tree number is " + this.numTree + " by thread " + Thread.currentThread().getId());
	}
	
	public void addTree(GATree t){
		trees.add(t);
	}
	
	@Override
	public Message clone() {
		SetRouteMessage msg = new SetRouteMessage(SenderID, hopToSink, numTree);
		msg.trees.addAll(trees);
		return msg;
	}

}
